# Generated by Django 2.2.6 on 2020-06-28 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('old_price', models.CharField(blank=True, max_length=255, null=True)),
                ('new_price', models.CharField(max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
                ('visibility', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='accessories/')),
                ('use_in_assembly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssemblyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('checked_out', models.BooleanField(default=False)),
                ('accessories', models.ManyToManyField(related_name='user_assembly', to='assembly.Accessory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssemblyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField()),
                ('approved', models.BooleanField(default=False)),
                ('decline', models.BooleanField(default=False)),
                ('declined_reason', models.TextField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('cart', models.ManyToManyField(related_name='orders', to='assembly.UserAssemblyCart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='assembly.AssemblyComponent'),
        ),
    ]
